id: DEE4D1E6E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-04-08T09:38:54+00:00'
last_modified: '2022-05-30T06:45:28.863333+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    c6c7:
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      order: 26
      base_file: c6c7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
