id: P57D3868E
initial_creation_type: ocr
source_metadata:
  volumes:
    11be2df76ab44642ae3b30366ff985b0:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ''
      total_pages: 1902
      volume_number: 26
